export const NOTIFICATIONS_LIST_REQUEST = 'NOTIFICATIONS_LIST_REQUEST';
export const NOTIFICATIONS_LIST_SUCCESS = 'NOTIFICATIONS_LIST_SUCCESS';
export const NOTIFICATIONS_LIST_FAIL = 'NOTIFICATIONS_LIST_FAIL';

export const NOTIFICATION_MARK_READ_REQUEST = 'NOTIFICATION_MARK_READ_REQUEST';
export const NOTIFICATION_MARK_READ_SUCCESS = 'NOTIFICATION_MARK_READ_SUCCESS';
export const NOTIFICATION_MARK_READ_FAIL = 'NOTIFICATION_MARK_READ_FAIL';

export const NOTIFICATION_DELETE_REQUEST = 'NOTIFICATION_DELETE_REQUEST';
export const NOTIFICATION_DELETE_SUCCESS = 'NOTIFICATION_DELETE_SUCCESS';
export const NOTIFICATION_DELETE_FAIL = 'NOTIFICATION_DELETE_FAIL';

export const NOTIFICATIONS_CLEAR_REQUEST = 'NOTIFICATIONS_CLEAR_REQUEST';
export const NOTIFICATIONS_CLEAR_SUCCESS = 'NOTIFICATIONS_CLEAR_SUCCESS';
export const NOTIFICATIONS_CLEAR_FAIL = 'NOTIFICATIONS_CLEAR_FAIL';

export const NOTIFICATIONS_RESET = 'NOTIFICATIONS_RESET';
